#define yy_create_buffer qtp_create_buffer
#define yy_delete_buffer qtp_delete_buffer
#define yy_scan_buffer qtp_scan_buffer
#define yy_scan_string qtp_scan_string
#define yy_scan_bytes qtp_scan_bytes
#define yy_flex_debug qtp_flex_debug
#define yy_init_buffer qtp_init_buffer
#define yy_flush_buffer qtp_flush_buffer
#define yy_load_buffer_state qtp_load_buffer_state
#define yy_switch_to_buffer qtp_switch_to_buffer
#define yyin qtpin
#define yyleng qtpleng
#define yylex qtplex
#define yyout qtpout
#define yyrestart qtprestart
#define yytext qtptext
#define yywrap qtpwrap

#line 20 "main.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
static yyconst short int yy_accept[135] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       44,   42,   37,   36,   38,   42,   41,   42,   42,   20,
       19,   20,   20,   20,   20,   20,   20,   21,   43,   14,
       23,   17,   18,   23,   16,   23,   26,   29,   33,   35,
       34,   10,   12,   11,   13,    0,    0,    0,    0,    0,
       39,   40,   19,    0,    0,    0,    0,    0,    0,    0,
       14,    0,   15,   15,   26,   29,   33,   35,   34,   10,
        0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,    0,    0,   22,    1,   31,    0,    0,   27,

        0,    0,   24,    0,    0,    0,    8,    0,    0,    0,
       22,    2,    0,   30,    0,   25,    5,    0,    0,    4,
        3,    0,   28,    0,    0,    0,    0,    0,    6,    7,
        9,    0,   32,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    8,    1,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,   11,   12,
        1,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   14,    1,    1,   10,    1,   15,   16,   17,   18,

       19,   20,   21,   21,   22,   21,   21,   23,   21,   24,
       25,   26,   21,   27,   28,   29,   30,   31,   21,   32,
       21,   21,   33,    1,   34,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[35] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    4,
        3,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    5
    } ;

static yyconst short int yy_base[149] =
    {   0,
        0,   33,   66,   93,  121,    0,  155,    0,  256,  255,
      254,  253,  252,  249,  276,  275,  198,  194,    0,    6,
      120,  291,  291,  291,  291,  113,  291,    7,   83,  291,
      112,  105,   79,   86,    0,   82,   83,  291,  291,    0,
      291,  291,  291,   99,  291,  189,    0,    0,    0,    6,
       16,    0,  291,  291,  291,   98,   83,   81,    0,   88,
      291,  291,  100,   87,    2,   70,   82,   72,   71,   63,
        0,   78,    0,    0,    0,    0,    0,   25,   39,    0,
       82,   67,   15,   82,   67,   56,   46,   65,   62,   61,
       75,   52,   60,   49,   48,   67,  291,   53,   53,  291,

       48,   66,   50,   65,   38,   37,  291,   59,   58,   44,
       52,  291,   56,  291,   29,  291,  291,   34,   33,  291,
      291,   37,  291,   28,   40,   28,   26,    4,  291,  291,
      291,   11,  291,  291,  223,  228,  233,  238,  243,  248,
      253,  258,    1,  263,  267,  271,  275,  280
    } ;

static yyconst short int yy_def[149] =
    {   0,
      135,  135,  136,  136,  134,    5,  134,    7,  137,  137,
      138,  138,  139,  139,  140,  140,  141,  141,  142,  142,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  143,
      134,  134,  134,  134,  134,  134,  144,  145,  146,  134,
      134,  147,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      143,  134,  148,   46,  144,  145,  146,  134,  134,  147,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,    0,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134
    } ;

static yyconst short int yy_nxt[326] =
    {   0,
      134,   23,   24,   53,   71,   25,   54,   78,   78,   53,
       55,   26,   54,   27,  133,   57,   55,   79,   79,   84,
       88,   67,  132,   85,   68,   58,   78,   78,   59,  131,
       89,  130,   28,   29,   23,   24,   98,   60,   25,   61,
       79,   79,   99,  129,   26,  128,   27,  103,  103,  111,
      111,  103,  103,  111,  111,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,   28,   29,   31,  117,  116,
      115,  114,  113,   32,  112,  110,  109,  108,  107,  106,
      105,  104,  102,  101,   33,  100,   97,   34,   35,   96,
       95,   36,   94,   37,   31,   93,   92,   91,   90,   87,

       32,   63,   86,   83,   82,   81,   72,   70,   69,   66,
       65,   33,   64,   63,   34,   35,   62,   56,   36,  134,
       37,   38,   39,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   38,   38,   41,   39,   41,   42,   41,
       41,   43,   44,   41,   41,   45,   41,   41,   41,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   41,   41,   73,
       73,   73,   73,   73,   73,   39,   73,   73,   74,   39,

       73,   73,   73,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   73,   73,   22,   22,   22,   22,   22,   30,   30,
       30,   30,   30,   47,   47,   47,   47,   47,   48,   48,
       48,   48,   48,   49,   49,   49,   49,   49,   50,   50,
       50,   50,   50,   51,   51,   51,   51,   51,   52,   52,
       52,   52,   52,   75,   75,   75,   75,   76,   76,   76,
       76,   77,   77,   77,   77,   80,   39,   39,   80,   80,
       73,   73,   39,   73,   73,   39,   39,   39,   39,   39,
       21,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134
    } ;

static yyconst short int yy_chk[326] =
    {   0,
        0,    1,    1,   19,  143,    1,   19,   50,   50,   20,
       19,    1,   20,    1,  132,   28,   20,   51,   51,   59,
       65,   35,  128,   59,   35,   28,   78,   78,   28,  127,
       65,  126,    1,    1,    2,    2,   83,   28,    2,   28,
       79,   79,   83,  125,    2,  124,    2,   87,   87,   95,
       95,  103,  103,  111,  111,  122,  119,  118,  115,  113,
      110,  109,  108,  106,  105,    2,    2,    3,  104,  102,
      101,   99,   98,    3,   96,   94,   93,   92,   91,   90,
       89,   88,   86,   85,    3,   84,   82,    3,    3,   81,
       72,    3,   70,    3,    4,   69,   68,   67,   66,   64,

        4,   63,   60,   58,   57,   56,   44,   37,   36,   34,
       33,    4,   32,   31,    4,    4,   29,   26,    4,   21,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   46,
       46,   46,   46,   46,   46,   18,   46,   46,   46,   17,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,  135,  135,  135,  135,  135,  136,  136,
      136,  136,  136,  137,  137,  137,  137,  137,  138,  138,
      138,  138,  138,  139,  139,  139,  139,  139,  140,  140,
      140,  140,  140,  141,  141,  141,  141,  141,  142,  142,
      142,  142,  142,  144,  144,  144,  144,  145,  145,  145,
      145,  146,  146,  146,  146,  147,   16,   15,  147,  147,
      148,  148,   14,  148,  148,   13,   12,   11,   10,    9,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,

      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  134,  134,  134
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#define INITIAL 0
#line 2 "main.l"
#define T_PREPARE 5
#define T_TRUE 1
#define T_FALSE 0

#define MAX_PARAMS 300
#define MAX_PARAMS_LEN 200
#define MAX_RES 500000
#define MAX_INCLUDE_DEPTH 50
#define RELEASE "stable release"
#define FAULT_OFFSET 15
#define FAULT_OFFSET_NULL FAULT_OFFSET-1

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "qstr.h"
#include "parse.h"
#include "utils.h"
#include "../config.h"
char parms[MAX_PARAMS][MAX_PARAMS_LEN];
int parms_count;

char sources[MAX_PARAMS][MAX_PARAMS_LEN];
int sources_count=0;

char funct[MAX_PARAMS_LEN];
int uniproc=0,uinternal=0;
char inclvar[MAX_PARAMS_LEN];
char res[MAX_RES],dupres[MAX_RES],tempres[MAX_RES];
char do_cmd[MAX_PARAMS][MAX_PARAMS_LEN];
int do_cmd_internal[MAX_PARAMS];
char ibuf[MAX_RES];
int qtp_do_cmd_count=0;
int elif=0;
int qtp_toolline=1;
size_t res_count;
int is_while,is_i, is_at_start=T_PREPARE;
int qtp_fwrite_counter=0;

FILE *fout_c,*fout_h;
struct gengetopt_args_info pinfo;
char option[201];

// Includes...
YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH+1];
int include_stack_ptr = 0;

#define htmlcomment 1
#define declare 2
#define params 3
#define replacer 4
#define ifelse 5
#define include 6
#define endtag 7
#define endinclude 8
#define sorce 9

#line 557 "main.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 54 "main.l"



#line 712 "main.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 135 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 291 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "main.l"
{
	if (!(pinfo.extended_given)) BEGIN (htmlcomment); else
	{
		qtp_fwrite_counter+=4;strfcat (res,"<!--",MAX_RES,&res_count);
		if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
	}
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "main.l"
BEGIN (htmlcomment);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=0;uinternal=0;
	do_cmd_internal[qtp_do_cmd_count] = 0;
	BEGIN (declare);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=0;uinternal=0;
	do_cmd_internal[qtp_do_cmd_count] = 0;
	BEGIN (declare);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=0;uinternal=0;
	do_cmd_internal[qtp_do_cmd_count] = 0;
	BEGIN (declare);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 85 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=1;uinternal=0;
	do_cmd_internal[qtp_do_cmd_count] = 0;
	BEGIN (declare);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=0;uinternal=1;
	do_cmd_internal[qtp_do_cmd_count] = 1;
	BEGIN (declare);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "main.l"
{
	parms_count=0;is_while=0;is_i=0;uniproc=0;uinternal=2;
	do_cmd_internal[qtp_do_cmd_count] = 2;
	BEGIN (declare);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 103 "main.l"
{
	BEGIN (sorce);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "main.l"
{
	str1cpy (sources[sources_count++],qtptext,MAX_PARAMS_LEN);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "main.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 113 "main.l"
;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "main.l"
{
	int i;
	if (sources_count) {
		for (i=0;i<sources_count;i++)
			fprintf (fout_c,"#include \"%s\"\n",sources[i]);
		fprintf (fout_c,"\n");
		sources_count=0;
	}
	is_at_start = T_PREPARE;
	BEGIN (htmlcomment);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "main.l"
{
	str1cpy (funct,qtptext,MAX_PARAMS_LEN);
	if (!uniproc)
	    snprintf (do_cmd[qtp_do_cmd_count++],MAX_PARAMS_LEN,"%s%s_%s",
			    pinfo.prefix_arg,
			    pinfo.out_arg,
			    qtptext);
	else
	    str1cpy (do_cmd[qtp_do_cmd_count++],qtptext,MAX_PARAMS_LEN);
	BEGIN (params);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 139 "main.l"
str1cpy (parms[parms_count++],qtptext,MAX_PARAMS_LEN);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "main.l"
{
	int i;
	if (qtp_fwrite_counter==0) res[res_count-FAULT_OFFSET_NULL] = '\0';
	str1cpy (dupres,res,MAX_RES);
	if (uniproc) {
		fprintf (fout_c,"void %s_do (%s);\n",funct,option);
	} else {
		if (!uinternal) 
			fprintf (fout_c,"void %s%s_%s_do (%s);\n",
					pinfo.prefix_arg,
					pinfo.out_arg,
					funct,option);
		fprintf (fout_c,"void %s%s_%s (",
				pinfo.prefix_arg,
				pinfo.out_arg,
				funct);
		fprintf (fout_h,"void %s%s_%s (",
				pinfo.prefix_arg,
				pinfo.out_arg,
				funct);
	}
	if (parms_count>0) {
		fprintf (fout_c,"%s",parms[0]);
		fprintf (fout_h,"%s",parms[0]); 
	}
	for (is_i=1;is_i<parms_count;is_i++) {
		fprintf (fout_c,", %s",parms[is_i]);
		fprintf (fout_h,", %s",parms[is_i]);
	}
	if (!uniproc) { 
	    fprintf (fout_c,") {\n");
	    if (!pinfo.nostd_given) {
		if (!pinfo.contentlength_given) {
		    replace (dupres,"[[[FWRITE]]]","fwrite",1);
		    replace (dupres,"[[[OFILE]]]","stdout",1);
		    if (is_at_start==T_FALSE) fprintf (fout_c,"\tfwrite (\"");
		    fprintf (fout_c,"%s",dupres);
		    if (qtp_fwrite_counter>0) 
			    fprintf (fout_c,"\",%d,1,stdout);\n",
					    qtp_fwrite_counter);
		} else {
		    replace (dupres,"[[[FWRITE]]]","qcm_inject",1);
		    replace (dupres,"[[[OFILE]]]","stdout",1);
		    if (is_at_start==T_FALSE)
			    fprintf (fout_c,"\tqcm_inject (\"");
		    fprintf (fout_c,"%s",dupres);
		    if (qtp_fwrite_counter>0)
			    fprintf (fout_c,"\",%d,1,stdout);\n",
					    qtp_fwrite_counter);
		}
	    }
	    if (!pinfo.contentlength_given)
		for (i=0;i<pinfo.file_given;i++) {
		    fprintf (fout_c,"\tif (!%s) return;\n",pinfo.file_arg[i]);
		    str1cpy (dupres,res,MAX_RES);
		    replace (dupres,"[[[FWRITE]]]","fwrite",1);
		    replace (dupres,"[[[OFILE]]]",pinfo.file_arg[i],1);
		    if (is_at_start==T_FALSE)
			    fprintf (fout_c,"\tfwrite (\"");
		    fprintf (fout_c,"%s",dupres);
		    if (qtp_fwrite_counter>0)
			    fprintf (fout_c,"\",%d,1,%s);\n",
					    qtp_fwrite_counter,
					    pinfo.file_arg[i]);
		}	
	    fprintf (fout_c,"}\n");
	    fprintf (fout_h,");\n");
	}
	res[0] = '\0'; res_count = 0;
	qtp_fwrite_counter=0;
	is_at_start = T_PREPARE;
	BEGIN(htmlcomment);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 215 "main.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 216 "main.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 218 "main.l"
;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 219 "main.l"
;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 220 "main.l"
;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 222 "main.l"
BEGIN(INITIAL);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 224 "main.l"
{
	fprintf (stderr,"Error: Unexpected '%s' at line %d !\n",
			qtptext,
			qtp_toolline);
	exit (0);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 231 "main.l"
BEGIN(INITIAL);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 233 "main.l"
BEGIN (replacer);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 235 "main.l"
{
	    // Only fast mode
	    if(qtp_fwrite_counter) {
			strfcat(res,"\"",MAX_RES,&res_count);
			snprintf (tempres,MAX_RES,",%d,1,[[[OFILE]]]);\n",
					qtp_fwrite_counter);
			strfcat(res,tempres,MAX_RES,&res_count);
	    } else {
		    if (is_at_start==T_PREPARE) is_at_start = T_TRUE;
		    else res_count-=FAULT_OFFSET;
	    }
	    if (!pinfo.contentlength_given) {
		strfcat(res,"\tfprintf([[[OFILE]]],",MAX_RES,&res_count);
		strfcat(res,qtptext,MAX_RES,&res_count);
		strfcat(res,");\n\t[[[FWRITE]]] (\"",MAX_RES,&res_count);
	    } else {
		snprintf (ibuf,MAX_RES,"\tqcm_printf (");
		strfcat (res,ibuf,MAX_RES,&res_count);
		strfcat(res,qtptext,MAX_RES,&res_count);
		snprintf (ibuf,MAX_RES,");\n\t[[[FWRITE]]] (\"");
		strfcat(res,ibuf,MAX_RES,&res_count);
	    }


	    qtp_fwrite_counter=0;
		BEGIN (endtag);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 263 "main.l"
{
		elif=0;
		BEGIN (ifelse);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 268 "main.l"
{
		elif=1;
		BEGIN (ifelse);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 273 "main.l"
{
		// Only fast mode
		if(qtp_fwrite_counter) {
			strfcat(res,"\"",MAX_RES,&res_count);
			snprintf (tempres,MAX_RES,",%d,1,[[[OFILE]]]);\n\t",
					qtp_fwrite_counter);
			strfcat(res,tempres,MAX_RES,&res_count);
		} else {
			if (is_at_start==T_PREPARE) is_at_start = T_TRUE; 
			else {
				res_count-=FAULT_OFFSET;
				if (res_count<0) res_count=0;
			}
		}
		if (elif)
			strfcat(res,"} else if(",MAX_RES,&res_count);
		else
			strfcat(res,"if(",MAX_RES,&res_count);
		strfcat(res,qtptext,MAX_RES,&res_count);
		strfcat(res,") {\n\t",MAX_RES,&res_count);

		// It's fast mode.
		strfcat(res,"[[[FWRITE]]] (\"",MAX_RES,&res_count);

		qtp_fwrite_counter=0;
		BEGIN (endtag);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 301 "main.l"
{
		// It's fast mode.
		if(qtp_fwrite_counter) {
			strfcat(res,"\"",MAX_RES,&res_count);
			snprintf (tempres,MAX_RES,",%d,1,[[[OFILE]]]);\n\t",
					qtp_fwrite_counter);
			strfcat(res,tempres,MAX_RES,&res_count);
		} else
		if (is_at_start==T_PREPARE) is_at_start = T_TRUE; 
		else res_count-=FAULT_OFFSET;

		strfcat(res,"} else {\n\t",MAX_RES,&res_count);

		// It's fast mode.
		strfcat(res,"[[[FWRITE]]] (\"",MAX_RES,&res_count);

		qtp_fwrite_counter=0;
		BEGIN (endtag);
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 321 "main.l"
{
		// Only fast mode.
		if(qtp_fwrite_counter) {
			strfcat(res,"\"",MAX_RES,&res_count);
			snprintf (tempres,MAX_RES,",%d,1,[[[OFILE]]]);\n\t",
					qtp_fwrite_counter);
			strfcat(res,tempres,MAX_RES,&res_count);
		} else
		if (is_at_start==T_PREPARE) is_at_start = T_TRUE;
		else res_count-=FAULT_OFFSET;

		strfcat(res,"}\n\t",MAX_RES,&res_count);

		// It's fast mode.
		strfcat(res,"[[[FWRITE]]] (\"",MAX_RES,&res_count);

		qtp_fwrite_counter=0;
		BEGIN (endtag);
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 341 "main.l"
BEGIN(include);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(htmlcomment):
case YY_STATE_EOF(declare):
case YY_STATE_EOF(params):
case YY_STATE_EOF(replacer):
case YY_STATE_EOF(ifelse):
case YY_STATE_EOF(include):
case YY_STATE_EOF(endtag):
case YY_STATE_EOF(endinclude):
case YY_STATE_EOF(sorce):
#line 343 "main.l"
{
	if (--include_stack_ptr<0) yyterminate(); else
	{
	    qtp_delete_buffer(YY_CURRENT_BUFFER);
	    qtp_switch_to_buffer (include_stack[include_stack_ptr]);
	}
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 352 "main.l"
{
		str1cpy (inclvar,qtptext,MAX_PARAMS_LEN);

		BEGIN (endinclude);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 358 "main.l"
{

		if (include_stack_ptr == MAX_INCLUDE_DEPTH) {
		    fprintf (stderr,"Include max depth reached!\n");
		    exit (1);
		}
		include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;
		
		qtpin = fopen (inclvar,"r");
		if (!qtpin) {
		    fprintf (stderr,"Cant open [%s] file!!!\n",inclvar);
		    exit (1);
		}
		
		qtp_switch_to_buffer(qtp_create_buffer (qtpin, YY_BUF_SIZE));
		BEGIN (INITIAL);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 376 "main.l"
{
		BEGIN (INITIAL);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 380 "main.l"
;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 381 "main.l"
{
	qtp_toolline++;qtp_fwrite_counter+=2;
	strfcat (res,"\\r\\n",MAX_RES,&res_count);
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 385 "main.l"
{
	qtp_fwrite_counter++;strfcat (res,"\\\"",MAX_RES,&res_count);
	if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 389 "main.l"
{
	qtp_fwrite_counter++;strfcat (res,"{",MAX_RES,&res_count);
	if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 393 "main.l"
{
	qtp_fwrite_counter++;strfcat (res,"}",MAX_RES,&res_count);
	if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 397 "main.l"
{
	qtp_fwrite_counter++;strfcat (res,"\\\\",MAX_RES,&res_count);
	if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 401 "main.l"
{
	qtp_fwrite_counter++;strfcat (res,qtptext,MAX_RES,&res_count);
	if (is_at_start!=T_TRUE) is_at_start = T_FALSE;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 406 "main.l"
ECHO;
	YY_BREAK
#line 1294 "main.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 135 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 135 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 134);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 406 "main.l"


int qtpwrap() { return 1; }

void qtp_show_about() {
	printf ("QTP (Qlang Template Preprocessor) version %s (%s)\n"
		"[ This tool is part of QPLATFORM project. ]\n\n"
		"Copyrght (c) 2003,2004,2006,2007  ainmarh labs\n\n",
			VERSION,
			OS_NAME);
}

int main (int argc, char **argv)
{

	char fname[201],*ptr;int i;
	res_count = 0;res[0] = '\0';

	parse (argc,argv,&pinfo);
	
	if (pinfo.userarg_given) snprintf (option,200,"void *userarg");
	else option[0]='\0';

	qtpin = fopen (pinfo.source_arg,"r");

	if (!qtpin) {
		qtp_show_about();
		printf ("Error: Can't open input file [%s]...\n\n",
				pinfo.source_arg);
		return 0;
	}
	
	if (!pinfo.out_given) {
		pinfo.out_arg = malloc (strlen(pinfo.source_arg)+2);
		str1cpy (pinfo.out_arg,
				pinfo.source_arg,
				strlen(pinfo.source_arg)+2);
	}
	
	if ( (ptr = strchr (pinfo.out_arg,'.')) ) ptr[0] = '\0';
	
	if (pinfo.out_c_given) snprintf (fname,200,"%s",pinfo.out_c_arg);
	else snprintf (fname,200,"%s.c",pinfo.out_arg);
	fout_c = fopen (fname,"w");
	if (!fout_c) {
		qtp_show_about();
		printf ("Error: Can't open output file [%s]...\n\n",fname);
		return 0;
	}

	if (pinfo.out_h_given) snprintf (fname,200,"%s",pinfo.out_h_arg);
	else snprintf (fname,200,"%s.h",pinfo.out_arg);
	fout_h = fopen (fname,"w");
	if (!fout_h) {
		qtp_show_about();
		printf ("Error: Can't open output file [%s]...\n\n",fname);
		return 0;
	}
	fprintf (stderr,"Processing %s...\n",pinfo.source_arg);
	fprintf (fout_c,"/* Generated from "
			"[%s] by QTP (version %s %s) */\n\n",
			pinfo.source_arg,
			VERSION,
			OS_NAME);
	fprintf (fout_h,"/* Generated from "
			"[%s] by QTP (version %s %s) */\n\n",
			pinfo.source_arg,
			VERSION,
			OS_NAME);
	if (!pinfo.nocgix_given) 
		fprintf(fout_c,"#include <string.h>\n"
				"#include <stdio.h>\n"
				"#include <cgix.h>\n"
				"#include <qcm_internal.h>\n");
	else
		fprintf(fout_c,"#include <string.h>\n"
				"#include <stdio.h>\n");
	for (i=0;i<pinfo.include_given;i++)
		fprintf (fout_c,"#include \"%s\"\n",pinfo.include_arg[i]);
	if (pinfo.contentlength_given) {
		fprintf (fout_c,"extern char *qtp_content;\n");
		fprintf (fout_c,"extern char *qtp_content_temp;\n");
		fprintf (fout_c,"extern size_t qtp_content_length;\n");
		fprintf (fout_c,"extern size_t qtp_content_i;\n");
		fprintf (fout_c,"extern size_t qcm_cl_internal;\n");
		fprintf (fout_c,"extern size_t qcm_cl_temp;\n");
	}
	for (i=0;i<pinfo.file_given;i++)
		fprintf (fout_c,"extern FILE *%s;\n",pinfo.file_arg[i]);
	fprintf (fout_c,"\n");
	if ((!pinfo.nostd_given)&&(pinfo.contentlength_given)) {
		fprintf (fout_c,"void %s%s_commit () "
				"{\n\tprintf (\"Content-Length: %%lld\\r\\n\""
				",(long long)qtp_content_length);\n",
				pinfo.prefix_arg,
				pinfo.out_arg);
		fprintf (fout_c,"\tfwrite (qtp_content,1,qtp_content_length"
				",stdout);\n");
		for (i=0;i<pinfo.file_given;i++) 
			fprintf (fout_c,"\tfwrite (qtp_content,1,"
					"qtp_content_length,%s);\n",
					pinfo.file_arg[i]);
		fprintf (fout_c,"}\n\n");
	}
	qtplex();
	for (i=0;i<qtp_do_cmd_count;i++)
		if (do_cmd_internal[i]==1) 
			fprintf (fout_c,"void %s_do(%s) {\n\t%s();\n}\n\n",
					do_cmd[i],
					option,
					do_cmd[i]);
	fprintf (fout_c,"\nvoid %s%s(%s) {\n",
			pinfo.prefix_arg,
			pinfo.out_arg,
			option);
	fprintf (fout_h,"\nvoid %s%s(%s);\n",
			pinfo.prefix_arg,
			pinfo.out_arg
			,option);
	if (!(pinfo.nostd_given)) fprintf (fout_c,"\tprintf (\"\\r\\n\");\n");
	for (i=0;i<qtp_do_cmd_count;i++)
		if (do_cmd_internal[i]!=2) fprintf (fout_c,"\t%s_do(%s);\n",
				do_cmd[i],
				option[0]?"userarg":"");
	if (pinfo.contentlength_given) {
		fprintf (fout_c,"\t%s%s_commit();\n",
				pinfo.prefix_arg,
				pinfo.out_arg);
		fprintf (fout_c,"\tqtp_content_length=0;\n");
	}
	fprintf (fout_c,"}\n");
	fclose (fout_c);
	fclose (fout_h);
	return 0;
}
