/*
  File autogenerated by gengetopt version 2.18
  generated with the following command:
  gengetopt -fparse -Fparse -iparse.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "parse.h"

const char *gengetopt_args_info_purpose = "QTP (Qlang Template Preprocessor).\n  [ This tool is part of QPLATFORM project. ]\n\n  Copyright (c) 2003,2004,2006,2007  ainmarh labs";

const char *gengetopt_args_info_usage = "Usage: qtp [OPTIONS]...";

const char *gengetopt_args_info_help[] = {
  "  -h, --help            Print help and exit",
  "  -V, --version         Print version and exit",
  "  -s, --source=STRING   source filename (*.q) for processing",
  "  -o, --out=STRING      project name (default source filename before dot)",
  "  -c, --out-c=STRING    result filename (*.c)",
  "  -r, --out-h=STRING    result header filename (*.h)",
  "  -f, --file=STRING     internal file for writing cached output",
  "  -p, --prefix=STRING   function prefix (like qtp_)  (default=`')",
  "  -i, --include=STRING  include .h file in template",
  "  -l, --contentlength   Insert 'Content-Length:' tag",
  "  -n, --nostd           no std output from Q-Lang cgi daemon",
  "      --nocgix          No CGIX support enabled",
  "  -u, --userarg         Enable passing of user argument",
  "  -x, --extended        Use <!--- (three minus) as delimiter",
  "  -m, --module          Include QUERY-module in source",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
parse_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);

static int
parse_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

struct string_list
{
  char * arg;
  char *orig;
  struct string_list * next;
};

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->source_given = 0 ;
  args_info->out_given = 0 ;
  args_info->out_c_given = 0 ;
  args_info->out_h_given = 0 ;
  args_info->file_given = 0 ;
  args_info->prefix_given = 0 ;
  args_info->include_given = 0 ;
  args_info->contentlength_given = 0 ;
  args_info->nostd_given = 0 ;
  args_info->nocgix_given = 0 ;
  args_info->userarg_given = 0 ;
  args_info->extended_given = 0 ;
  args_info->module_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->source_arg = NULL;
  args_info->source_orig = NULL;
  args_info->out_arg = NULL;
  args_info->out_orig = NULL;
  args_info->out_c_arg = NULL;
  args_info->out_c_orig = NULL;
  args_info->out_h_arg = NULL;
  args_info->out_h_orig = NULL;
  args_info->file_arg = NULL;
  args_info->file_orig = NULL;
  args_info->prefix_arg = gengetopt_strdup ("");
  args_info->prefix_orig = NULL;
  args_info->include_arg = NULL;
  args_info->include_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->source_help = gengetopt_args_info_help[2] ;
  args_info->out_help = gengetopt_args_info_help[3] ;
  args_info->out_c_help = gengetopt_args_info_help[4] ;
  args_info->out_h_help = gengetopt_args_info_help[5] ;
  args_info->file_help = gengetopt_args_info_help[6] ;
  args_info->file_min = -1;
  args_info->file_max = -1;
  args_info->prefix_help = gengetopt_args_info_help[7] ;
  args_info->include_help = gengetopt_args_info_help[8] ;
  args_info->include_min = -1;
  args_info->include_max = -1;
  args_info->contentlength_help = gengetopt_args_info_help[9] ;
  args_info->nostd_help = gengetopt_args_info_help[10] ;
  args_info->nocgix_help = gengetopt_args_info_help[11] ;
  args_info->userarg_help = gengetopt_args_info_help[12] ;
  args_info->extended_help = gengetopt_args_info_help[13] ;
  args_info->module_help = gengetopt_args_info_help[14] ;
  
}

void
parse_print_version (void)
{
  printf ("%s %s\n", PARSE_PACKAGE, PARSE_VERSION);
}

void
parse_print_help (void)
{
  int i = 0;
  parse_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
parse_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

static void
parse_release (struct gengetopt_args_info *args_info)
{
  
  unsigned int i;
  if (args_info->source_arg)
    {
      free (args_info->source_arg); /* free previous argument */
      args_info->source_arg = 0;
    }
  if (args_info->source_orig)
    {
      free (args_info->source_orig); /* free previous argument */
      args_info->source_orig = 0;
    }
  if (args_info->out_arg)
    {
      free (args_info->out_arg); /* free previous argument */
      args_info->out_arg = 0;
    }
  if (args_info->out_orig)
    {
      free (args_info->out_orig); /* free previous argument */
      args_info->out_orig = 0;
    }
  if (args_info->out_c_arg)
    {
      free (args_info->out_c_arg); /* free previous argument */
      args_info->out_c_arg = 0;
    }
  if (args_info->out_c_orig)
    {
      free (args_info->out_c_orig); /* free previous argument */
      args_info->out_c_orig = 0;
    }
  if (args_info->out_h_arg)
    {
      free (args_info->out_h_arg); /* free previous argument */
      args_info->out_h_arg = 0;
    }
  if (args_info->out_h_orig)
    {
      free (args_info->out_h_orig); /* free previous argument */
      args_info->out_h_orig = 0;
    }
  if (args_info->file_arg)
    {
      for (i = 0; i < args_info->file_given; ++i)
        {
          if (args_info->file_arg [i])
            {
              free (args_info->file_arg [i]); /* free previous argument */
              args_info->file_arg [i] = 0;
            }
          if (args_info->file_orig [i])
            {
              free (args_info->file_orig [i]); /* free previous argument */
              args_info->file_orig [i] = 0;
            }
        }
      if (args_info->file_arg [0])
        free (args_info->file_arg [0]); /* free default string */
      free (args_info->file_arg); /* free previous argument */
      args_info->file_arg = 0;
      free (args_info->file_orig); /* free previous argument */
      args_info->file_orig = 0;
    }
  if (args_info->prefix_arg)
    {
      free (args_info->prefix_arg); /* free previous argument */
      args_info->prefix_arg = 0;
    }
  if (args_info->prefix_orig)
    {
      free (args_info->prefix_orig); /* free previous argument */
      args_info->prefix_orig = 0;
    }
  if (args_info->include_arg)
    {
      for (i = 0; i < args_info->include_given; ++i)
        {
          if (args_info->include_arg [i])
            {
              free (args_info->include_arg [i]); /* free previous argument */
              args_info->include_arg [i] = 0;
            }
          if (args_info->include_orig [i])
            {
              free (args_info->include_orig [i]); /* free previous argument */
              args_info->include_orig [i] = 0;
            }
        }
      if (args_info->include_arg [0])
        free (args_info->include_arg [0]); /* free default string */
      free (args_info->include_arg); /* free previous argument */
      args_info->include_arg = 0;
      free (args_info->include_orig); /* free previous argument */
      args_info->include_orig = 0;
    }
  
  clear_given (args_info);
}

int
parse_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", PARSE_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->source_given) {
    if (args_info->source_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "source", args_info->source_orig);
    } else {
      fprintf(outfile, "%s\n", "source");
    }
  }
  if (args_info->out_given) {
    if (args_info->out_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "out", args_info->out_orig);
    } else {
      fprintf(outfile, "%s\n", "out");
    }
  }
  if (args_info->out_c_given) {
    if (args_info->out_c_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "out-c", args_info->out_c_orig);
    } else {
      fprintf(outfile, "%s\n", "out-c");
    }
  }
  if (args_info->out_h_given) {
    if (args_info->out_h_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "out-h", args_info->out_h_orig);
    } else {
      fprintf(outfile, "%s\n", "out-h");
    }
  }
  if (args_info->file_orig)
    {
      for (i = 0; i < args_info->file_given; ++i)
        {
          if (args_info->file_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "file", args_info->file_orig [i]);
            }
        }
    }
  if (args_info->prefix_given) {
    if (args_info->prefix_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "prefix", args_info->prefix_orig);
    } else {
      fprintf(outfile, "%s\n", "prefix");
    }
  }
  if (args_info->include_orig)
    {
      for (i = 0; i < args_info->include_given; ++i)
        {
          if (args_info->include_orig [i])
            {
              fprintf(outfile, "%s=\"%s\"\n", "include", args_info->include_orig [i]);
            }
        }
    }
  if (args_info->contentlength_given) {
    fprintf(outfile, "%s\n", "contentlength");
  }
  if (args_info->nostd_given) {
    fprintf(outfile, "%s\n", "nostd");
  }
  if (args_info->nocgix_given) {
    fprintf(outfile, "%s\n", "nocgix");
  }
  if (args_info->userarg_given) {
    fprintf(outfile, "%s\n", "userarg");
  }
  if (args_info->extended_given) {
    fprintf(outfile, "%s\n", "extended");
  }
  if (args_info->module_given) {
    fprintf(outfile, "%s\n", "module");
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
parse_free (struct gengetopt_args_info *args_info)
{
  parse_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  char *tok, *ret;
  size_t len, num_of_escape;
  int i, j;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static char *
get_multiple_arg_token_next(const char *arg)
{
  char *tok;

  if (!arg)
    return NULL;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, int min, int max, const char *option_desc)
{
  int error = 0;

  if (option_given && ! (min < 0 && max < 0))
    {
      if (min >= 0 && max >= 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < min
              || option_given > max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min >= 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max >= 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
parse (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return parse2 (argc, argv, args_info, 0, 1, 1);
}

int
parse2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = parse_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      parse_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
parse_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (parse_required2(args_info, prog_name, NULL) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      parse_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
parse_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;

  /* checks for required options */
  if (! args_info->source_given)
    {
      fprintf (stderr, "%s: '--source' ('-s') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  if (check_multiple_option_occurrences(prog_name, args_info->file_given, args_info->file_min, args_info->file_max, "'--file' ('-f')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->include_given, args_info->include_min, args_info->include_max, "'--include' ('-i')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}

int
parse_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  char *multi_token, *multi_next; /* for multiple options */

  int i;        /* Counter */

  struct string_list * file_list = NULL,* file_new = NULL;
  struct string_list * include_list = NULL,* include_new = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    parse_init (args_info);

  parse_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "source",	1, NULL, 's' },
        { "out",	1, NULL, 'o' },
        { "out-c",	1, NULL, 'c' },
        { "out-h",	1, NULL, 'r' },
        { "file",	1, NULL, 'f' },
        { "prefix",	1, NULL, 'p' },
        { "include",	1, NULL, 'i' },
        { "contentlength",	0, NULL, 'l' },
        { "nostd",	0, NULL, 'n' },
        { "nocgix",	0, NULL, 0 },
        { "userarg",	0, NULL, 'u' },
        { "extended",	0, NULL, 'x' },
        { "module",	0, NULL, 'm' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVs:o:c:r:f:p:i:lnuxm", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          parse_print_help ();
          parse_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          parse_print_version ();
          parse_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* source filename (*.q) for processing.  */
          if (local_args_info.source_given)
            {
              fprintf (stderr, "%s: `--source' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->source_given && ! override)
            continue;
          local_args_info.source_given = 1;
          args_info->source_given = 1;
          if (args_info->source_arg)
            free (args_info->source_arg); /* free previous string */
          args_info->source_arg = gengetopt_strdup (optarg);
          if (args_info->source_orig)
            free (args_info->source_orig); /* free previous string */
          args_info->source_orig = gengetopt_strdup (optarg);
          break;

        case 'o':	/* project name (default source filename before dot).  */
          if (local_args_info.out_given)
            {
              fprintf (stderr, "%s: `--out' (`-o') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->out_given && ! override)
            continue;
          local_args_info.out_given = 1;
          args_info->out_given = 1;
          if (args_info->out_arg)
            free (args_info->out_arg); /* free previous string */
          args_info->out_arg = gengetopt_strdup (optarg);
          if (args_info->out_orig)
            free (args_info->out_orig); /* free previous string */
          args_info->out_orig = gengetopt_strdup (optarg);
          break;

        case 'c':	/* result filename (*.c).  */
          if (local_args_info.out_c_given)
            {
              fprintf (stderr, "%s: `--out-c' (`-c') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->out_c_given && ! override)
            continue;
          local_args_info.out_c_given = 1;
          args_info->out_c_given = 1;
          if (args_info->out_c_arg)
            free (args_info->out_c_arg); /* free previous string */
          args_info->out_c_arg = gengetopt_strdup (optarg);
          if (args_info->out_c_orig)
            free (args_info->out_c_orig); /* free previous string */
          args_info->out_c_orig = gengetopt_strdup (optarg);
          break;

        case 'r':	/* result header filename (*.h).  */
          if (local_args_info.out_h_given)
            {
              fprintf (stderr, "%s: `--out-h' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->out_h_given && ! override)
            continue;
          local_args_info.out_h_given = 1;
          args_info->out_h_given = 1;
          if (args_info->out_h_arg)
            free (args_info->out_h_arg); /* free previous string */
          args_info->out_h_arg = gengetopt_strdup (optarg);
          if (args_info->out_h_orig)
            free (args_info->out_h_orig); /* free previous string */
          args_info->out_h_orig = gengetopt_strdup (optarg);
          break;

        case 'f':	/* internal file for writing cached output.  */
          local_args_info.file_given++;
        
          multi_token = get_multiple_arg_token(optarg);
          multi_next = get_multiple_arg_token_next (optarg);
        
          while (1)
            {
              file_new = (struct string_list *) malloc (sizeof (struct string_list));
              file_new->next = file_list;
              file_list = file_new;
              file_new->arg = gengetopt_strdup (multi_token);
              file_new->orig = multi_token;
        
              if (multi_next)
                {
                  multi_token = get_multiple_arg_token(multi_next);
                  multi_next = get_multiple_arg_token_next (multi_next);
                  local_args_info.file_given++;
                }
              else
                break;
            }
          break;

        case 'p':	/* function prefix (like qtp_).  */
          if (local_args_info.prefix_given)
            {
              fprintf (stderr, "%s: `--prefix' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->prefix_given && ! override)
            continue;
          local_args_info.prefix_given = 1;
          args_info->prefix_given = 1;
          if (args_info->prefix_arg)
            free (args_info->prefix_arg); /* free previous string */
          args_info->prefix_arg = gengetopt_strdup (optarg);
          if (args_info->prefix_orig)
            free (args_info->prefix_orig); /* free previous string */
          args_info->prefix_orig = gengetopt_strdup (optarg);
          break;

        case 'i':	/* include .h file in template.  */
          local_args_info.include_given++;
        
          multi_token = get_multiple_arg_token(optarg);
          multi_next = get_multiple_arg_token_next (optarg);
        
          while (1)
            {
              include_new = (struct string_list *) malloc (sizeof (struct string_list));
              include_new->next = include_list;
              include_list = include_new;
              include_new->arg = gengetopt_strdup (multi_token);
              include_new->orig = multi_token;
        
              if (multi_next)
                {
                  multi_token = get_multiple_arg_token(multi_next);
                  multi_next = get_multiple_arg_token_next (multi_next);
                  local_args_info.include_given++;
                }
              else
                break;
            }
          break;

        case 'l':	/* Insert 'Content-Length:' tag.  */
          if (local_args_info.contentlength_given)
            {
              fprintf (stderr, "%s: `--contentlength' (`-l') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->contentlength_given && ! override)
            continue;
          local_args_info.contentlength_given = 1;
          args_info->contentlength_given = 1;
          break;

        case 'n':	/* no std output from Q-Lang cgi daemon.  */
          if (local_args_info.nostd_given)
            {
              fprintf (stderr, "%s: `--nostd' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->nostd_given && ! override)
            continue;
          local_args_info.nostd_given = 1;
          args_info->nostd_given = 1;
          break;

        case 'u':	/* Enable passing of user argument.  */
          if (local_args_info.userarg_given)
            {
              fprintf (stderr, "%s: `--userarg' (`-u') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->userarg_given && ! override)
            continue;
          local_args_info.userarg_given = 1;
          args_info->userarg_given = 1;
          break;

        case 'x':	/* Use <!--- (three minus) as delimiter.  */
          if (local_args_info.extended_given)
            {
              fprintf (stderr, "%s: `--extended' (`-x') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->extended_given && ! override)
            continue;
          local_args_info.extended_given = 1;
          args_info->extended_given = 1;
          break;

        case 'm':	/* Include QUERY-module in source.  */
          if (local_args_info.module_given)
            {
              fprintf (stderr, "%s: `--module' (`-m') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->module_given && ! override)
            continue;
          local_args_info.module_given = 1;
          args_info->module_given = 1;
          break;


        case 0:	/* Long option with no short option */
          /* No CGIX support enabled.  */
          if (strcmp (long_options[option_index].name, "nocgix") == 0)
          {
            if (local_args_info.nocgix_given)
              {
                fprintf (stderr, "%s: `--nocgix' option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
                goto failure;
              }
            if (args_info->nocgix_given && ! override)
              continue;
            local_args_info.nocgix_given = 1;
            args_info->nocgix_given = 1;
            break;
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", PARSE_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  if (local_args_info.file_given && file_list)
    {
      struct string_list *tmp;
      args_info->file_arg = (char * *) realloc (args_info->file_arg, (args_info->file_given + local_args_info.file_given) * sizeof (char *));
      args_info->file_orig = (char **) realloc (args_info->file_orig, (args_info->file_given + local_args_info.file_given) * sizeof (char *));
      for (i = (local_args_info.file_given - 1); i >= 0; --i)
        {
          tmp = file_list;
          args_info->file_arg [i + args_info->file_given] = file_list->arg;
          args_info->file_orig [i + args_info->file_given] = file_list->orig;
          file_list = file_list->next;
          free (tmp);
        }
    }
  
  if (local_args_info.include_given && include_list)
    {
      struct string_list *tmp;
      args_info->include_arg = (char * *) realloc (args_info->include_arg, (args_info->include_given + local_args_info.include_given) * sizeof (char *));
      args_info->include_orig = (char **) realloc (args_info->include_orig, (args_info->include_given + local_args_info.include_given) * sizeof (char *));
      for (i = (local_args_info.include_given - 1); i >= 0; --i)
        {
          tmp = include_list;
          args_info->include_arg [i + args_info->include_given] = include_list->arg;
          args_info->include_orig [i + args_info->include_given] = include_list->orig;
          include_list = include_list->next;
          free (tmp);
        }
    }
  

  args_info->file_given += local_args_info.file_given;
  local_args_info.file_given = 0;
  args_info->include_given += local_args_info.include_given;
  local_args_info.include_given = 0;
  
  if (check_required)
    {
      error += parse_required2 (args_info, argv[0], additional_error);
    }

  parse_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  if (file_list)
    {
      struct string_list *tmp;
      while (file_list)
        {
          tmp = file_list;
          free (file_list->arg);
          free (file_list->orig);
          file_list = file_list->next;
          free (tmp);
        }
    }
  if (include_list)
    {
      struct string_list *tmp;
      while (include_list)
        {
          tmp = include_list;
          free (include_list->arg);
          free (include_list->orig);
          include_list = include_list->next;
          free (tmp);
        }
    }
  
  parse_release (&local_args_info);
  return (EXIT_FAILURE);
}
